In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle


In [2]:
df = pd.read_csv('Iris_Dataset.csv')

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
X=df.loc[:,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'] ]   




In [5]:
df['Species'].replace(['Iris-setosa'],0,inplace=True)


In [6]:
df['Species'].replace(['Iris-virginica'],2,inplace=True)

In [7]:
df['Species'].replace(['Iris-versicolor'],1,inplace=True)


In [8]:
y=df['Species']

In [9]:
df = shuffle(df)

In [10]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
106  107            4.9           2.5            4.5           1.7        2
46    47            5.1           3.8            1.6           0.2        0
30    31            4.8           3.1            1.6           0.2        0
45    46            4.8           3.0            1.4           0.3        0
133  134            6.3           2.8            5.1           1.5        2
14    15            5.8           4.0            1.2           0.2        0
71    72            6.1           2.8            4.0           1.3        1
132  133            6.4           2.8            5.6           2.2        2
56    57            6.3           3.3            4.7           1.6        1
143  144            6.8           3.2            5.9           2.3        2
138  139            6.0           3.0            4.8           1.8        2
65    66            6.7           3.1            4.4           1.4        1
0      1            5.1           3.5            1.4           0.2        0
61    62            5.9           3.0            4.2           1.5        1
32    33            5.2           4.1            1.5           0.1        0
35    36            5.0           3.2            1.2           0.2        0
62    63            6.0           2.2            4.0           1.0        1
127  128            6.1           3.0            4.9           1.8        2
80    81            5.5           2.4            3.8           1.1        1
16    17            5.4           3.9            1.3           0.4        0
68    69            6.2           2.2            4.5           1.5        1
123  124            6.3           2.7            4.9           1.8        2
149  150            5.9           3.0            5.1           1.8        2
94    95            5.6           2.7            4.2           1.3        1
101  102            5.8           2.7            5.1           1.9        2
24    25            4.8           3.4            1.9           0.2        0
104  105            6.5           3.0            5.8           2.2        2
92    93            5.8           2.6            4.0           1.2        1
5      6            5.4           3.9            1.7           0.4        0
57    58            4.9           2.4            3.3           1.0        1
..   ...            ...           ...            ...           ...      ...
26    27            5.0           3.4            1.6           0.4        0
120  121            6.9           3.2            5.7           2.3        2
81    82            5.5           2.4            3.7           1.0        1
118  119            7.7           2.6            6.9           2.3        2
108  109            6.7           2.5            5.8           1.8        2
83    84            6.0           2.7            5.1           1.6        1
25    26            5.0           3.0            1.6           0.2        0
50    51            7.0           3.2            4.7           1.4        1
109  110            7.2           3.6            6.1           2.5        2
89    90            5.5           2.5            4.0           1.3        1
10    11            5.4           3.7            1.5           0.2        0
134  135            6.1           2.6            5.6           1.4        2
22    23            4.6           3.6            1.0           0.2        0
8      9            4.4           2.9            1.4           0.2        0
86    87            6.7           3.1            4.7           1.5        1
129  130            7.2           3.0            5.8           1.6        2
125  126            7.2           3.2            6.0           1.8        2
51    52            6.4           3.2            4.5           1.5        1
84    85            5.4           3.0            4.5           1.5        1
19    20            5.1           3.8            1.5           0.3        0
64    65            5.6           2.9            3.6  

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[17  0  0]
 [ 0 10  1]
 [ 0  1  9]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       0.91      0.91      0.91        11
          2       0.90      0.90      0.90        10

avg / total       0.95      0.95      0.95        38



C:\Users\Swarnendu\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [14]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,predictions)

In [15]:
accuracy

0.9473684210526315